config/routes.rb
Sociweb::Application.routes.draw do

  resources :projects do
    resources :segments
  end

  root :to => "home#show"

end

app/models/project.rb
class Project < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  def index
    segments = [
      {
        :id       => 1,
        :position => 2,
        :source   => "Les chasseurs sachant chasser chassent leurs chiens dans des sachets",
        :target   => "the hunters that can hunt hunt their dogs in bags"
      },
      {
        :id       => 2,
        :position => 1,
        :source   => "bonjour monde",
        :target   => ""
      },
      {
        :id       => 3,
        :position => 0,
        :source   => "Les sanglots longs des violons de l'automne bercent mon coeur d'une langueur monotone",
        :target   => ""
      },
      {
        :id       => 4,
        :position => 3,
        :source   => "J'ai rêvé, une fois !",
        :target   => "I have a dream !"
      },
      {
        :id       => 5,
        :position => 4,
        :source   => "Ta mère est une jeune startup dans le hainaut",
        :target   => "Your mother is a young startup in Hainaut"
      }
    ]
    render :json => segments.sort { |segment1, segment2| segment1[:position] <=> segment2[:position] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_carousel.html.erb
<section id="home-slide" class="section home-page">
	<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
			<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
			<li data-target="#carousel-example-generic" data-slide-to="1"></li>
			<li data-target="#carousel-example-generic" data-slide-to="2"></li>
		</ol>
		<!-- Wrapper for slides -->
		<div class="carousel-inner">
			<div class="item active">
				<%= image_tag "carousel/01.png" %>
				<div class="carousel-caption">
					<h3>picture 1</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag "carousel/02.png" %>
				<div class="carousel-caption">
					<h3>picture 2</h3>
				</div>
			</div>
			<div class="item">
				<%= image_tag "carousel/03.png" %>
				<div class="carousel-caption">
					<h3>picture 3</h3>
				</div>
			</div>
		</div>
		<!-- Controls -->
		<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left"></span>
		</a>
		<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right"></span>
		</a>
	</div>
</section>

app/views/home/_modalSignIn.html.erb
<!-- modal Login -->
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h1 class="modal-title text-center" id="">Sign In</h1>

			</div>
			<div class="modal-body">
				<form role="form" id="form-sign-in">
					<div class="form-group">
						<label for="email-sign-in">Email address</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
							<input type="email" class="form-control" id="email-sign-in" placeholder="Enter email">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="password-sign-in">Password</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
							<input type="password" class="form-control" id="password-sign-in" placeholder="Enter password">
						</div>
					</div><!-- /.form-group -->
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-lg btn-block">Ok</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

app/views/home/_modalSignUp.html.erb
<!-- modal Inscription -->
<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h1 class="modal-title text-center" id="">Sign Up</h1>

			</div>
			<div class="modal-body">

				<form role="form" id="form-sign-up">
					<div class="form-group">
						<label for="name-sign-up">Name</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-user"></i></span>
							<input type="text" class="form-control" id="name-sign-up" placeholder="Enter name">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="email-sign-up">Email address</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
							<input type="email" class="form-control" id="email-sign-up" placeholder="Enter email">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="password-sign-up">Password</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
							<input type="password" class="form-control" id="password-sign-up" placeholder="Enter password">
						</div>
					</div><!-- /.form-group -->
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-lg btn-block">Valider</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

app/views/home/_modal_sign_in.html.erb
<!-- modal Login -->
<div class="modal fade" id="signin-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h1 class="modal-title text-center" id="">Sign In</h1>

			</div>
			<div class="modal-body">
				<form role="form" id="form-sign-in">
					<div class="form-group">
						<label for="email-sign-in">Email address</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
							<input type="email" class="form-control" id="email-sign-in" placeholder="Enter email">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="password-sign-in">Password</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
							<input type="password" class="form-control" id="password-sign-in" placeholder="Enter password">
						</div>
					</div><!-- /.form-group -->
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-lg btn-block">Ok</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

app/views/home/_modal_sign_up.html.erb
<!-- modal Inscription -->
<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h1 class="modal-title text-center" id="">Sign Up</h1>

			</div>
			<div class="modal-body">

				<form role="form" id="form-sign-up">
					<div class="form-group">
						<label for="name-sign-up">Name</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-user"></i></span>
							<input type="text" class="form-control" id="name-sign-up" placeholder="Enter name">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="email-sign-up">Email address</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
							<input type="email" class="form-control" id="email-sign-up" placeholder="Enter email">
						</div>
					</div><!-- /.form-group -->
					<div class="form-group">
						<label for="password-sign-up">Password</label>
						<div class="input-group input-group-lg">
							<span class="input-group-addon"><i class="fa fa-asterisk"></i></span>
							<input type="password" class="form-control" id="password-sign-up" placeholder="Enter password">
						</div>
					</div><!-- /.form-group -->
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary btn-lg btn-block">Valider</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal --> 

app/views/home/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-static-top" role="navigation" id="nav-main">
	<div class="container">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-main-items">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Socitrad</a>
		<div class="collapse navbar-collapse nav-main-items">
			<ul class="nav navbar-nav navbar-right">
				<li class="nav-items-first"><a href="#">item1</a></li>
				<li class="nav-items-first"><a href="#">item2</a></li>
				<li class="nav-items-first"><a href="#">item3</a></li>
				<li class="margin-xs-left" data-toggle="modal" data-target="#signin-modal"><button type="button" class="btn btn-default navbar-btn">Se connecter</button></li>
			</ul>
		</div>
	</div>
</nav>

app/views/home/_nav_home.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-static-top" role="navigation" id="nav-main-home">
	<div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-main-items">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="#">Socitrad</a>
		<div class="collapse navbar-collapse nav-main-items">
			<ul class="nav navbar-nav navbar-right">
				<li class="nav-items-first"><a href="#">item1</a></li>
				<li class="nav-items-first"><a href="#">item2</a></li>
				<li class="nav-items-first"><a href="#">item3</a></li>
				<li class="margin-xs-left" data-toggle="modal" data-target="#signin-modal"><button type="button" class="btn btn-default navbar-btn">Se connecter</button></li>
			</ul>
		</div>
	</div>
</nav>

app/views/home/_partners.html.erb
<section class="section navbar navbar-default home-page" id="clients-banner">
	<div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
		<ul class="row text-center">
			<div class="col-md-3">
				<a href="#" class="thumbnail partner">
					<img alt="" src="/assets/partners/phonoid.png">
				</a>
			</div>
			<li class="col-md-3">
				<a href="#" class="thumbnail partner">
					<img alt="" src="/assets/partners/80-limit.png">
				</a>
			</li>
			<li class="col-md-3">
				<a href="#" class="thumbnail partner">
					<img alt="" src="/assets/partners/phonoid.png">
				</a>
			</li>
			<li class="col-md-3">
				<a href="#" class="thumbnail partner">
					<img alt="" src="/assets/partners/80-limit.png">
				</a>
			</li>
		</ul>
	</div>
</section>

app/views/home/_pitch.html.erb
<section id="home-header" class="home-page">
	<div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
		<div class="jumbotron">
			<h1>Hello World !</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. In explicabo neque ipsa itaque accusantium eaque molestiae sequi voluptates repellat quidem. Aliquam, eveniet, iure dolor tenetur vero modi nostrum veritatis possimus!</p>
			<h2><a class="btn btn-primary btn-warning btn-lg btn-inscription" href="#" data-toggle="modal" data-target="#signup-modal">S'inscrire</a></h2>
		</div>
	</div>
</section>

app/views/home/_services.html.erb
<section id="home-services" class="section">
	<div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
		<div class="page-header text-center">
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit !</p>
		</div>
		<div class="row margin-xs-bottom">
			<div class="col-md-4">
				<div class="fa fa-globe"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, doloremque eaque possimus delectus dignissimos accusamus ipsam aut illo. Tenetur, odit deleniti minima velit aperiam ut obcaecati consectetur voluptatum beatae explicabo.</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fa fa-cog"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis, quaerat perspiciatis incidunt recusandae architecto ut iusto totam excepturi laudantium. Deserunt, officiis blanditiis ea impedit asperiores laborum eveniet aliquid numquam perferendis.</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fa fa-pencil"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, ipsum qui molestiae voluptates hic tenetur laboriosam assumenda magni dolor id? Voluptates, quaerat atque saepe pariatur tempore ipsam eveniet obcaecati blanditiis?</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
		</div>
		<div class="row margin-md-bottom">
			<div class="col-md-4">
				<div class="fa fa-file"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eaque, reiciendis, nobis vel nesciunt praesentium voluptatem recusandae sint possimus ex amet consectetur quidem exercitationem labore blanditiis iste maiores rerum minus doloremque.</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fa fa-folder-open"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, corrupti eligendi ea iste nulla placeat aperiam maxime. Quisquam, cumque error est amet recusandae neque harum distinctio laudantium. Nesciunt, optio, quasi.</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fa fa-briefcase"></div>
				<div class="caption">
					<h3>Lorem ipsum</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, ipsa, at repellat ducimus officiis omnis consectetur ea nesciunt alias inventore eaque quibusdam nostrum tenetur nam provident voluptatibus sequi ratione atque.</p>
					<p>
						<a class="btn btn-primary" alt="read more" href="#">Read More</a> 
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
		<div class="text-left signup pager">
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit !</p>
			<a class="btn btn-primary btn-warning btn-lg" href="#" data-toggle="modal" data-target="#signup-modal">S'inscrire</a>
		</div>
	</div>
</section>

app/views/home/show.html.erb
<div class="page">
	<%= render 'home/nav_home' %>
	<%= render 'home/modal_sign_in' %>
	<%= render 'home/modal_sign_up' %>
	<%= render 'home/pitch' %>
	<%= render 'home/partners' %>
	<%= render 'home/carousel' %>
	<%= render 'home/services' %>
</div>

app/views/layouts/_footer.html.erb
<section id="footer" class="section">
  <div class="col-lg-8 col-lg-offset-2 col-sm-8 col-sm-offset-2">
    <nav class="navbar">
      <ul class="nav navbar-nav navbar-left">

        <li id="copyright" class="navbar-text"><small>&copy;<%= Time.now.year %> socitrad.com All Rights Res.</small></li>
        <li class="navbar-text">
          <small>
            <select>
              <option>Lorem Ipsum</option>
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>
          </small>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><small>Lorem Ipsum</small></a></li>
        <li><a href="#"><small>Lorem Ipsum</small></a></li>
      </ul>
    </nav>
  </div>
</section>

app/views/layouts/_nav_member.html.erb
<nav id="nav-main-member" class="navbar navbar-default navbar-fixed-top navbar-static-top" role="navigation">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-main">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Socitrad", "#home", :class => 'navbar-brand' %>

    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse no-padding-right" id="nav-main">
      <ul class="nav navbar-nav navbar-right navbar-btn no-padding col-lg-2 col-sm-3">
        <li class="dropdown btn-block">
          <a href="#" id="dropdown-member" class="dropdown-toggle btn btn-default" data-toggle="dropdown">
            <div class="col-lg-10 col-sm-10">
              <i class="fa fa-cog"></i>
              <span>Member</span>
            </div>
            <div class="no-padding-left">
              <b class="caret"></b>
              <span class="sr-only">Toggle Dropdown</span>
            </div>
          </a>
          <ul class="dropdown-menu">
            <li><a href="#"><i class="fa fa-user"></i><span>Profil</span></a></li>
            <li class="divider"></li>
            <li><a href="#">Deconnexion</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Ok</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sociweb</title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<%= csrf_meta_tags %>
</head>

<body id="<%= "#{params[:controller]}-#{params[:action]}" %>" ng-app="mainApp">
	<%= yield %>
	<%= render "layouts/footer" %>
</body>

<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.3/angular.min.js"></script>
<%= javascript_include_tag "application" %>
</html>

app/views/projects/_index_aside.html.erb
<div class="col-lg-4 col-sm-3 col-xs-6 no-padding-right">
	<figure class="avatar col-lg-8 col-lg-offset-4 col-sm-12" id="avatar-profil">
		<ul class="list-unstyled">
			<li class=""><%= image_tag "members/avatar.png", alt:"avatar member", class:"img-thumbnail"%></li>
			<li class="edit-avatar">
				<a href="#" class="btn btn-default edit" role="button" data-toggle="modal" data-target="#uploadpicture-modal">edit</a>
			</li>
		</ul>
		<figcaption class="text-center">
			<h2><small>nom du membre</small></h2>
			<p><a href="#">adress@mail.com</a></p>
		</figcaption>
	</figure>
</div>

app/views/projects/_index_listing.html.erb
<div class="col-lg-8 col-sm-9">
  <div class="panel-group" id="projects">
    <ul class="list-group pull-left col-lg-12 col-sm-12 no-padding no-margin" id="projects-heading">
      <li class="list-group-item col-lg-12 col-sm-12 pull-left no-padding">
        <h4 class="no-margin pull-left col-lg-12 col-sm-12 no-padding">
          <span class="pull-left">Projects</span>
          <span class="badge pull-left margin-xs-left"><%= @projects.count %></span>
        </h4 >
        <button class="btn btn-default btn-lg btn-primary pull-right" id="btn-new-project" data-toggle="modal" data-target="#newproject-modal">new project</button>
      </li>
    </ul>

    <%# @projects.each do |project| %>
      <%#= render 'project', :project => project %>
    <%# end %>

    <%= render @projects %>
  </div>
</div>

app/views/projects/_interface_bar.html.erb
<section class="row navbar-fixed-bottom" id="translation-bar">
	<aside class="col-lg-3 col-sm-3 side-left">
		<div class="side-left-wrap">
			<div class="list-group no-margin">
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Lorem Ipsum</h4>
					<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Lorem Ipsum</h4>
					<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Lorem Ipsum</h4>
					<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
				</a>
				<a href="#" class="list-group-item">
					<h4 class="list-group-item-heading">Lorem Ipsum</h4>
					<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
				</a>
			</div>
		</div>
	</aside>
	<div class="col-lg-6 col-sm-6 translation-bar-main">
		<form role="form">
			<div class="form-group no-margin">
				<div class="well" id="segment-original">
					<blockquote class="no-margin">Segment à traduire</blockquote>
				</div>
				<label for="segmentTranslate" class="sr-only">Zone de traduction</label>
				<textarea id="segmentTranslate" class="form-control"></textarea>
			</div>
		</form>
	</div>
	<!-- Nav tabs -->
	<aside class="col-lg-3 col-sm-3 side-right">
		<div class="nav-content">
			<ul class="nav nav-tabs  no-padding">
				<li class="active"><a href="#comments" data-toggle="tab">Commentaires</a></li>
				<li><a href="#historic" data-toggle="tab">Historique</a></li>
			</ul>
		</div>
		<!-- Tab panes -->
		<div class="tab-content">
			<div class="tab-pane active" id="comments">
				<div class="list-group">
					<a href="#" class="list-group-item">
						<h4 class="list-group-item-heading">Lorem Ipsum</h4>
						<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
					</a>
					<a href="#" class="list-group-item">
						<h4 class="list-group-item-heading">Lorem Ipsum</h4>
						<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
					</a>
				</div>
			</div>
			<div class="tab-pane" id="historic">
				<div class="list-group">
					<a href="#" class="list-group-item">
						<h4 class="list-group-item-heading">Lorem Ipsum</h4>
						<p class="list-group-item-text">Lorem ipsum dolor sit.</p>
					</a>
				</div>
			</div>
		</div>
	</aside>
</section>

app/views/projects/_project.html.erb
<div class="panel panel-default" id="project-<%= project.id %>">
  <div class="panel-heading pull-left panel-document" data-toggle="collapse" data-parent="#projects" data-target="#project-<%= project.id %>-content">

    <div class="panel-title pull-left">
      <div class="project-title col-lg-6 col-sm-7">
        <%= link_to "<small>#{project.name}</small>".html_safe, project_path(project), :class => 'document-version' %>
      </div>
      <div class="col-lg-3 col-sm-2">
        <span data-toggle="tooltip" title="nombre de segments traduits"><small>36/60</small></span>
      </div>
      <div class="col-lg-3 col-sm-3">
        <div class="panel-title progress progress-striped" data-toggle="tooltip" title="60% Complete">
          <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
          </div>
        </div>
      </div>
    </div>

  </div>

  <div id="project-<%= project.id %>-content" class="pull-left panel-collapse collapse col-lg-12 col-sm-12 no-padding">

    <ul class=" panel-body list-group no-margin">
      <li class="list-group-item pull-left col-lg-12 col-sm-12">
        <ul class="list-unstyled">
          <li class="col-lg-7 col-sm-5"><a href="#" class="document-version">EN > NL</a></li>
          <li class="col-lg-3 col-sm-3">
            <ul class="list-unstyled" data-toggle="tooltip" title="nombre de segments traduits">
              <li>
                <small>36/60</small>
              </li>
            </ul>
          </li>
          <li class="col-lg-2 col-sm-4 no-padding">
            <ul class="progress progress-striped col-lg-12 col-sm-12 no-padding pull-left" data-toggle="tooltip" title="60% Complete">
              <li class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
              </li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="list-group-item pull-left col-lg-12 col-sm-12">
        <ul class="list-unstyled">
          <li class="col-lg-7 col-sm-5"><a href="#" class="document-version">EN > ES</a></li>
          <li class="col-lg-3 col-sm-3">
            <ul class="list-unstyled" data-toggle="tooltip" title="nombre de segments traduits">
              <li>
                <small>36/60</small>
              </li>
            </ul>
          </li>
          <li class="col-lg-2 col-sm-4 no-padding">
            <ul class="progress progress-striped col-lg-12 col-sm-12 no-padding pull-left" data-toggle="tooltip" title="60% Complete">
              <li class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
              </li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</div>